ARG         IMAGE_BASE

FROM        $IMAGE_BASE
MAINTAINER  Mark Barinstein <mark.barinstein@gmail.com>
ARG         INSTALLCMD=/setup/install.sh

COPY        cfg-nr/* /setup/
RUN         --mount=type=secret,id=secret chmod +x $INSTALLCMD && $INSTALLCMD

EXPOSE      50000 
USER        db2inst1
WORKDIR     /database/config/db2inst1
ENTRYPOINT  ["/setup/startup.sh"]
